[theme]
font = "Roboto:https://fonts.googleapis.com/css2?family=Roboto&display=swap"
primaryColor = "#89cc96"
chartCategoricalColors = [
    "#00468A",
    "#4787E5",
    "#89cc96",
    "#C4E38A",
    "#2467B8",
    "#68AABE",
    "#A7D890",
]
chartSequentialColors = [
    "#00468A",
    "#4787E5",
    "#89cc96",
    "#C4E38A",
    "#2467B8",
    "#68AABE",
    "#A7D890", 
]